### ISSUE TITLE
Eager loading Attachments?

### ISSUE THREAD

**Issue by hundredwatt** [rails/activestorage#20]
Since this library associates attachments to records without using ActiveRecord associations, eager loading with `includes` does not work:

```ruby
  test "eager load attachments" do
    @second_user = User.create!(name: 'Jason')

    assert User.includes(:attachment).to_a
  end
```

Result:
```
  1) Error:
ActiveStorage::AttachmentsTest#test_eager_load_attachments:
ActiveRecord::AssociationNotFoundError: Association named 'attachment' was not found on User; perhaps you misspelled it?
```

A use case for this would be a Users#index page that lists all users in a table and shows their avatar next to the user. The current approach would result an "N + 1" query problem as the Attachment for each User would be queried individually from the database.

**Comment by dhh** [comment]
Agree. This requires us to make GlobalID referenced associations first-class in Active Record. Which is a good idea anyway! Because it sidesteps the normal issue of trying to eager load polymorphic associations.

**Comment by kaspth** [comment]
@kamipo 👆😊

**Comment by kaspth** [comment]
Wrote up a more elaborate draft here: https://github.com/rails/rails/issues/29729 — do expand!

I've set it up as a 5.2 release blocker, so we'll be sure to look at it. I'll close this.
