### ISSUE TITLE
Supporting Additional Services

### ISSUE THREAD

**Issue by jeffreyguenther** [rails/activestorage#37]
Rather than clog #36 with an off topic discussion I have started a separate issue regarding the usage of gems to add support for additional services.

Having used thoughtbot/administrate that uses a similar approach for adding extra functionality to the dashboards, I think this approach works well for adding features. The only struggle I had with the approach was when they broke out a feature into a gem that really should have been in core. In their case, the image thumbnail view. 

As long as the services that cover the majority of cases (as is the Rails way), I think you're golden. Like ActiveRecord, I'd like to see support out of the box for the most "popular services" So it just works. Wanna do something weird, you'll need to write your own service.

I think supporting S3, AWS, Azure, and OpenStack give you great coverage. OpenStack can provide the bridge to ton of niche services. The [fog](http://fog.io/) gem can be used for this.

With this position, I think we should also try to write a guide on how to implement your own service. As would be first-time rails contributor, I can take a stab at this as I attempt the OpenStack service. My extra green eyes might help bring the right things to the surface.

**Comment by dhh** [comment]
The plan is for Active Storage to ship with all the features in the box, like Active Record. But also, like Active Record, adapters for additional services should be done as external gems. Active Record ships with adapters for SQLite/MySQL/PostgreSQL in the box. Then everything beyond that is a gem. I'd like to continue with that.

For me, the adapters that make sense in the box for Active Storage is disk/s3/gcs/azure. OpenStack can be the first additional gem. Feel free to use activestorage-openstack as the name for that.

**Comment by jeffreyguenther** [comment]
Ok, I'd prefer it bundled, but I understand your position. 😀 Either way we can still provide the value to others.

Do you have a sense of how you'd like to make others aware that third-party services exist?
Would you be interested in a PR for a "How to write a service" section for the README? Creating these services seems to me like it will be a little more common than writing an Active Record adapter. New cloud services seem pretty common.

**Comment by dhh** [comment]
Yeah, would definitely like to link up all the other adapters in the
README. Also happy to have a section about how to write a service. Though
we should start considering what the Rails Guide looks like for this.
That's generally a better place to evolve in than just the README.

**Comment by jeffreyguenther** [comment]
Sounds good.

My thought is to write the document in the style of a guide and include it in this repo for the time being. Then when the project is moved over to the main rails repo, we can move it into the guides folder. Does that work for you?

**Comment by dhh** [comment]
👌
