### ISSUE TITLE
File types / sizes / location

### ISSUE THREAD

**Issue by maikelnabil** [rails/activestorage#46]
Thank you guys, for working on this thing. I'm really excited about it. I'm wondering how to put some control on the uploads:
1. How to control which file extensions are allowed or not? I've just uploaded a pdf with this gem, and I don't want to allow this on my app.
2. How to control allowed file sizes and image dimensions?
3. Is there a way to upload the files to a folder in the AWS S3 bucket, and not to the root of the bucket?

**Comment by georgeclaghorn** [comment]
You can filter files by name, content type, size, etc. before attaching them:

```ruby
class AvatarsController < ApplicationController
  before_action :require_acceptable_image, only: :update

  def update
    Current.user.avatar.attach(params[:avatar])
    redirect_to Current.user
  end

  private
    def require_acceptable_image
      render 'edit' unless acceptable_avatar_image?(params[:avatar])
    end

    def acceptable_image?(file)
      file && file.content_type =~ /\Aimage\// && file.size <= 50.megabytes
    end
end
```

Use a library like [Dimensions](https://github.com/sstephenson/dimensions) to extract an image’s width and height.

I’m afraid there’s no way to upload files to an S3 bucket with a key prefix.

**Comment by maikelnabil** [comment]
Thanks a lot!
