### ISSUE TITLE
Add support for hosted S3 object storage

### ISSUE THREAD

**Issue by seanhandley** [rails/activestorage#47]
I currently do a lot of work with OpenStack and we run a Ceph cluster which can be accessed via an S3 compatibility layer using our own host name.

Since S3 is a published protocol, it doesn't necessarily follow that an Active Storage user will always want to use S3 storage against Amazon's cloud.

The Amazon SDK being used by Active Storage supports an additional `endpoint` parameter to enable support for hosted S3. This is the path that I take directly in my Rails apps at present - I would prefer to go via the ActiveStorage route in future since it'll simplify my code.

I'm going to be working on this change here: https://github.com/rails/activestorage/pull/48

If anyone on the Rails team has any thoughts on this change then please let me know 😄

**Comment by dhh** [comment]
Ah this provided the explanation for the other PR. I think @jeremy has another take that allows you to pass in a whole client object.

**Comment by seanhandley** [comment]
Ahh ok. I guess that'd still need some additional code regarding what goes into the yaml file?

**Comment by georgeclaghorn** [comment]
Closing because #48 was merged.
