### ISSUE TITLE
Can we get a Backblaze adapter out of the box?

### ISSUE THREAD

**Issue by nickjj** [rails/activestorage#49]
Not sure if this is the correct spot for this but I noticed you don't have an adapter for Backblaze.

They are a very attractive competitor to S3. For example they are 4x cheaper than S3 in storage and 2.5x cheaper for downloads. They've been around for a long time and are rock solid.

Pricing details on how they compare to S3 and Google Cloud:  
https://www.backblaze.com/b2/cloud-storage-pricing.html

General details on their S3-like service:  
https://www.backblaze.com/b2/cloud-storage.html

I know there's the whole "but if we support this, then where do we draw the line?" argument for supporting services but I really think these guys are popular enough to have it officially supported. It could also be a good excuse to write a really nice Backblaze connectivity gem because that's currently lacking.

**Comment by dhh** [comment]
Happy to see activestorage-backblaze as an additional gem 👍. We've decided for now to limit the adapters in the box to S3/GCS/Azure. All other adapters are to be provided as additional gems. Just like for Active Record we ship with SQLite/MySQL/PostgresSQL. All other adapters like MSSQL or Oracle are add-ons. 👍
