### ISSUE TITLE
Support for S3 server_side_encryption

### ISSUE THREAD

**Issue by baerjam** [rails/activestorage#50]
Thank you guys for the all work on this, it looks great so far!
It would be nice if we could set the server_side_encryption option on S3 uploads, ideally, on a per model basis. 

`object_for(key).put(body: io, content_md5: checksum, server_side_encryption: 'AES256')`

I'm happy to open a PR but I want to get some feedback on the best way to implement this or maybe you guys already have thought about this? I can see others wanting to pass additional options to aws calls in the future, as well.

Thanks!

**Comment by georgeclaghorn** [comment]
> I'm happy to open a PR but I want to get some feedback on the best way to implement this or maybe you guys already have thought about this?

The best way to get feedback is to open a PR. Please Do Investigate. :smile:
