### ISSUE TITLE
Install error in new project (not migrated)

### ISSUE THREAD

**Issue by ileri** [rails/activestorage#64]
I create a new rails project to try Active Storage. Followed the install steps in README. But it gave error in step 2. Because the project was untouched , so there is not any migrations and db/migrate not exist.

For trying to copy a file to non-existent directory, ruby gave `Errno::ENOENT: No such file or directory` error.

Full text of the error:

> Made storage and tmp/storage directories for development and testing
Copied default configuration to config/storage_services.yml
rails aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/u/asd/db/migrate/20170721060652_active_storage_create_tables.rb
/home/u/asd/bin/rails:9:in 'require'
/home/u/asd/bin/rails:9:in '<top (required)>'
/home/u/asd/bin/spring:15:in '<top (required)>'
bin/rails:3:in 'load'
bin/rails:3:in '\<main>'
Tasks: TOP => activestorage:install
(See full trace by running task with --trace)

**Comment by dixpac** [comment]
Hi @ileri ! You are probably installing `activestorage` from the ruby gems. Since this is the work in progress requiring the latest version from the master should fix the problem(_ruby gems version is not up to date_)

```ruby
# Your Gemfile
gem 'activestorage', git: "https://github.com/rails/activestorage.git"
```

**Comment by georgeclaghorn** [comment]
As @dixpac mentioned, this was fixed in https://github.com/rails/activestorage/commit/07a62e63bd4effb819fd641155578b07eb5557ed.
