### ISSUE TITLE
Fix variant-related tests

### ISSUE THREAD

**Issue by georgeclaghorn** [rails/activestorage#72]
They fail consistently in CI and on my machine, presumably due to platform differences. (MiniMagick produces different images in CI, on my machine, and on David’s machine.) I’ve temporarily skipped them in master.

/cc @dhh

**Comment by colorfulfool** [comment]
Wait, would `assert_same_image` ever work? JPEG is a lossy format, it produces images that look the same to humans, but they don't have to be identical bit-to-bit.

**Comment by dhh** [comment]
Unless JPEG is not deterministic, this should have the potential to work. But of course it would need all elements held stable. Which maybe isn't right.

So probably easier we just switch to PNG for these tests instead.
