### ISSUE TITLE
Shortcut for downsampling

### ISSUE THREAD

**Issue by colorfulfool** [rails/activestorage#75]
I like what David have done with Variants, but I would like to still have a shortcut like
```erb
<%= image_tag magazine.cover_photo.url(size: '600x400') %>
```
Because downsampling is the most common use-case. More common than making no transformations at all.
<br>
But maybe you have something else planned? Like extending `image_tag` to accept a Variant instance?
```erb
<%= image_tag magazine.cover_photo.variant(resize: '600x400') %>
```

**Comment by dhh** [comment]
I'd like to extend image_tag to accept a variant instead 👍.
