### ISSUE TITLE
Amend image_tag to resolve Blobs and Variants

### ISSUE THREAD

**Issue by dhh** [rails/activestorage#77]
These should just work:

```erb
  <%= image_tag Current.user.avatar %>
  <%= image_tag Current.user.avatar.variant(resize: "100x100") %>
```

Right now you have to manually call `url_for` to resolve `ActiveStorage::Blob` and `ActiveStorage::Variant` into strings that image_tag will take. Need to amend image_tag to take these classes.

**Comment by padi** [comment]
Can I take this on? Here's the rough sketch of what I'm going to do:

1. Install activestorage in the same way as you would in your recent open PR https://github.com/rails/rails/pull/29989.
2. Add test/s for `AssetTagHelper#image_tag` when passed an`ActiveStorage::Blob`. It will be similar to how `ActionView::Helpers::FormHelper#form_for` was tested when an `AR::Model` was passed in  https://github.com/rails/rails/blob/master/actionview/test/activerecord/form_helper_activerecord_test.rb
3. Add implementation.

**Comment by georgeclaghorn** [comment]
Feel free to work on this. It might be easiest to wait until Active Storage is folded into Rails proper.
