### ISSUE TITLE
Get more informations on direct_uploads

### ISSUE THREAD

**Issue by dixpac** [rails/activestorage#79]
Currently from the `DirectUploadsController` we return `{:url, :sgid}` which works fine with S3 and GCS since they sign all required fields in query_string. 
But, Azure require some informations to be passed in headers, currently that header is 
`x-ms-blob-type: "BlockBlob"`.

Can we return fatter response from the controller that contains `url, sgid, headers` and use him on the fontend somethig like this
```js
  fetch("/rails/active_storage/direct_uploads", { method: "POST", body: data }).then(r => r.json()).then(function(directUploadDetails) {
    const reader = new FileReader()

    reader.onload = function(event) {
      fetch(directUploadDetails["url"], { 
        method: "PUT",
        headers: directUploadDetails.headers, // something like this
        body: event.currentTarget.result}).then(function() {
          ...

      })
    }

    reader.readAsBinaryString(file)
  })
 
```

Also, I suppose there are other storage providers in the wild that are going to need something like this

**Comment by dhh** [comment]
Sounds like a good idea. Weak sauce by Azure not just to allow a complete
URL, but let's accommodate.

**Comment by georgeclaghorn** [comment]
cc @javan

**Comment by javan** [comment]
Can you have a look at https://github.com/rails/activestorage/pull/81 and see if the events it provides satisfy your needs? You can hook into the request before it starts and add additional headers:
```js
addEventListener("direct-upload:before-storage-request", event => {
  const { xhr } = event.detail
  xhr.setRequestHeader("x-ms-blob-type", "BlockBlob")
})
```

**Comment by dixpac** [comment]
@javan  first of all thank you for the beautiful work ❤️ 💚 

Hooking into `direct-upload:before-storage-request` will work, but it will require developers to know about this up-front, upload will not work out-of the box like s3 and gcs. We would have to add this azure use case to the [documentation](https://github.com/rails/activestorage/pull/36/files#diff-04c6e90faac2675aa89e2176d2eec7d8R137) (_if I understood your implementation correctly_ 😄 )

My idea was to change a direct_upload response a bit and instead of returning url and sgid only to return more informations, in this case headers. Those headers we could automatically add inside direct_upload, so developers will not need to know about the at all. It will work out-of the box!

Also, 3th party storage developers could hook their specific headers when writing external activestorage gems.

I will take a stab at my idea in the following days and see how it is going to look like 😃
